var OA_output = new Array(); 
OA_output['3'] = '';
OA_output['3'] += "<"+"script type=\"text/javascript\" src=\"https://s.skimresources.com/js/21603X797475X981.adunit.js\"><"+"/script><"+"div id=\'beacon_e43c204eba\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.linuxquestions.org/www/delivery/lg.php?bannerid=3&amp;campaignid=2&amp;zoneid=3&amp;loc=http%3A%2F%2Fwww.linuxquestions.org%2Fquestions%2Flinux-desktop-74%2Fjwm-window-manager-how-to-put-the-taskbar-on-the-top-of-the-monitor-774159%2F&amp;cb=e43c204eba\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['4'] = '';
OA_output['4'] += "<"+"script type=\"text/javascript\">\n";
OA_output['4'] += "var infolink_pid = 8393;\n";
OA_output['4'] += "var infolink_wsid = 1;\n";
OA_output['4'] += "<"+"/script>\n";
OA_output['4'] += "<"+"script type=\"text/javascript\" src=\"https://resources.infolinks.com/js/infolinks_main.js\"><"+"/script><"+"div id=\'beacon_48e9d356de\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.linuxquestions.org/www/delivery/lg.php?bannerid=5&amp;campaignid=4&amp;zoneid=4&amp;loc=http%3A%2F%2Fwww.linuxquestions.org%2Fquestions%2Flinux-desktop-74%2Fjwm-window-manager-how-to-put-the-taskbar-on-the-top-of-the-monitor-774159%2F&amp;cb=48e9d356de\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['5'] = '';
OA_output['5'] += "<"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['5'] += "e9 = new Object();\n";
OA_output['5'] += "e9.size = \"728x90\";\n";
OA_output['5'] += "//--><"+"/script>\n";
OA_output['5'] += "<"+"script type=\"text/javascript\" src=\"//tags.expo9.exponential.com/tags/LinuxQuestionsorg/ROS/tags.js\"><"+"/script><"+"div id=\'beacon_b1a3d1cd84\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.linuxquestions.org/www/delivery/lg.php?bannerid=6&amp;campaignid=5&amp;zoneid=5&amp;loc=http%3A%2F%2Fwww.linuxquestions.org%2Fquestions%2Flinux-desktop-74%2Fjwm-window-manager-how-to-put-the-taskbar-on-the-top-of-the-monitor-774159%2F&amp;cb=b1a3d1cd84\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['6'] = '';
OA_output['6'] += "<"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['6'] += "<"+"!-- LQ Bottom - New (suggested) -->\n";
OA_output['6'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['6'] += "style=\"display:inline-block;width:336px;height:280px\"\n";
OA_output['6'] += "data-ad-client=\"ca-pub-4420048478783872\"\n";
OA_output['6'] += "data-ad-slot=\"3227443407\"><"+"/ins>\n";
OA_output['6'] += "<"+"script>\n";
OA_output['6'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['6'] += "<"+"/script><"+"div id=\'beacon_8409c17aaa\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.linuxquestions.org/www/delivery/lg.php?bannerid=10&amp;campaignid=9&amp;zoneid=6&amp;loc=http%3A%2F%2Fwww.linuxquestions.org%2Fquestions%2Flinux-desktop-74%2Fjwm-window-manager-how-to-put-the-taskbar-on-the-top-of-the-monitor-774159%2F&amp;cb=8409c17aaa\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['7'] = '';
OA_output['7'] += "<"+"script type=\"text/javascript\">\n";
OA_output['7'] += "google_ad_client = \"ca-pub-4420048478783872\";\n";
OA_output['7'] += "google_ad_slot = \"2731986808\";\n";
OA_output['7'] += "google_ad_width = 728;\n";
OA_output['7'] += "google_ad_height = 90;\n";
OA_output['7'] += "<"+"/script>\n";
OA_output['7'] += "<"+"!-- LQ Main - Top Leaderboard -->\n";
OA_output['7'] += "<"+"script type=\"text/javascript\"\n";
OA_output['7'] += "src=\"//pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['7'] += "<"+"/script><"+"div id=\'beacon_86b1b249fe\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.linuxquestions.org/www/delivery/lg.php?bannerid=12&amp;campaignid=10&amp;zoneid=7&amp;loc=http%3A%2F%2Fwww.linuxquestions.org%2Fquestions%2Flinux-desktop-74%2Fjwm-window-manager-how-to-put-the-taskbar-on-the-top-of-the-monitor-774159%2F&amp;cb=86b1b249fe\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['8'] = '';
OA_output['8'] += "<"+"script type=\"text/javascript\"><"+"!--\n";
OA_output['8'] += "google_ad_client = \"pub-4420048478783872\";\n";
OA_output['8'] += "/* LQ Main - Side Wide Skyscraper */\n";
OA_output['8'] += "google_ad_slot = \"5452649278\";\n";
OA_output['8'] += "google_ad_width = 160;\n";
OA_output['8'] += "google_ad_height = 600;\n";
OA_output['8'] += "//-->\n";
OA_output['8'] += "<"+"/script>\n";
OA_output['8'] += "<"+"script type=\"text/javascript\" src=\"//pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['8'] += "<"+"/script><"+"div id=\'beacon_04120f0e0e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.linuxquestions.org/www/delivery/lg.php?bannerid=13&amp;campaignid=11&amp;zoneid=8&amp;loc=http%3A%2F%2Fwww.linuxquestions.org%2Fquestions%2Flinux-desktop-74%2Fjwm-window-manager-how-to-put-the-taskbar-on-the-top-of-the-monitor-774159%2F&amp;cb=04120f0e0e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['9'] = '';
OA_output['9'] += "<"+"script type=\"text/javascript\" src=\"https://ap.lijit.com/www/delivery/fpi.js?z=136509&u=linuxquestions&width=160&height=600\"><"+"/script><"+"div id=\'beacon_50a8734b17\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.linuxquestions.org/www/delivery/lg.php?bannerid=17&amp;campaignid=16&amp;zoneid=9&amp;loc=http%3A%2F%2Fwww.linuxquestions.org%2Fquestions%2Flinux-desktop-74%2Fjwm-window-manager-how-to-put-the-taskbar-on-the-top-of-the-monitor-774159%2F&amp;cb=50a8734b17\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['10'] = '';
OA_output['10'] += "<"+"script type=\"text/javascript\">\n";
OA_output['10'] += "google_ad_client = \"ca-pub-4420048478783872\";\n";
OA_output['10'] += "google_ad_slot = \"7020975802\";\n";
OA_output['10'] += "google_ad_width = 336;\n";
OA_output['10'] += "google_ad_height = 280;\n";
OA_output['10'] += "<"+"/script>\n";
OA_output['10'] += "<"+"!-- LQ Main - Content Medium Rectangle 336 -->\n";
OA_output['10'] += "<"+"script type=\"text/javascript\"\n";
OA_output['10'] += "src=\"//pagead2.googlesyndication.com/pagead/show_ads.js\">\n";
OA_output['10'] += "<"+"/script><"+"div id=\'beacon_058180703a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.linuxquestions.org/www/delivery/lg.php?bannerid=16&amp;campaignid=15&amp;zoneid=10&amp;loc=http%3A%2F%2Fwww.linuxquestions.org%2Fquestions%2Flinux-desktop-74%2Fjwm-window-manager-how-to-put-the-taskbar-on-the-top-of-the-monitor-774159%2F&amp;cb=058180703a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['11'] = '';
OA_output['11'] += "<"+"script src=\"//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&adInstanceId=35e5a127-2e9a-47f8-87d8-885b9d571005&storeId=customcomputer0e\"><"+"/script><"+"div id=\'beacon_b517998486\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.linuxquestions.org/www/delivery/lg.php?bannerid=127&amp;campaignid=90&amp;zoneid=11&amp;loc=http%3A%2F%2Fwww.linuxquestions.org%2Fquestions%2Flinux-desktop-74%2Fjwm-window-manager-how-to-put-the-taskbar-on-the-top-of-the-monitor-774159%2F&amp;cb=b517998486\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
