#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/apt/trusted.gpg.d/debian-ports-archive-2014.gpg 2016.01.25\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apt/trusted.gpg.d/debian-ports-archive-2015.gpg 2016.01.25\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apt/trusted.gpg.d/debian-ports-archive-2016.gpg 2018.01.05\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apt/trusted.gpg.d/debian-ports-archive-2017.gpg 2018.12.27\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apt/trusted.gpg.d/debian-ports-archive-2018.gpg 2019.11.05\~ -- "$@"
# End automatically added section
